### ISSUE TITLE
Bower Component

### ISSUE THREAD

**Issue by joshmedeski** [parkerbennett/stackicons#6]
Hi Parker, have you thought about making this available as a Bower component? It only takes a few minutes, I would love to play with it there :)

**Comment by cognitom** [comment]
+1

**Comment by gladson** [comment]
:+1:

**Comment by axe312ger** [comment]
Yes please! +1

**Comment by axe312ger** [comment]
People are still using bower in 2018? 😱 

> ...psst! While Bower is maintained, we recommend using Yarn and Webpack for front-end projects read how to migrate!
